name: CI - Quality Gate (Security + Code) and Build

on: [push, pull_request]

env:
  BACKEND_DIR: backend
  SONAR_HOST_URL: https://sonarcloud.io

jobs:
  scan_gitguardian:
    name: Scan (GitGuardian) - Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  scan_snyk:
    name: Scan (Snyk) - Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Snyk CLI
      - name: Setup Snyk
        uses: snyk/actions/setup@v1.0.0
        with:
          snyk-version: latest

      - name: Snyk test (fail only on High/Critical)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --severity-threshold=high

  scan_sonarcloud:
    name: Scan (SonarQube Cloud) - Quality Gate
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          # Qui impostiamo la password del database nel container
          MYSQL_ROOT_PASSWORD: admin 
          MYSQL_DATABASE: second_chance
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root -padmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (for Maven + Scanner)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "19"
          cache: maven

      - name: Sonar analysis (Maven)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -DskipTests -DskipITs verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}

      - name: Quality Gate (fail workflow if ERROR)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          python3 - <<'PY'
          import os, time, re, json, urllib.request, base64, glob

          token = os.environ["SONAR_TOKEN"]
          def req(url):
            r = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
            with urllib.request.urlopen(r) as f:
              return json.loads(f.read().decode("utf-8"))

          # Maven scanner writes report-task.txt under target/sonar/
          candidates = glob.glob("**/target/sonar/report-task.txt", recursive=True)
          if not candidates:
            raise SystemExit("report-task.txt not found (expected **/target/sonar/report-task.txt)")
          report = candidates[0]

          with open(report, "r", encoding="utf-8") as f:
            txt = f.read()

          m = re.search(r"ceTaskUrl=(.+)", txt)
          if not m:
            raise SystemExit("ceTaskUrl not found in report-task.txt")
          ceTaskUrl = m.group(1).strip()

          # wait for background task completion
          for _ in range(60):
            data = req(ceTaskUrl)
            status = data["task"]["status"]
            if status in ("SUCCESS", "FAILED", "CANCELED"):
              break
            time.sleep(3)
          else:
            raise SystemExit("Timeout waiting for Sonar background task")

          if status != "SUCCESS":
            raise SystemExit(f"Sonar task status: {status}")

          analysisId = data["task"]["analysisId"]
          qg = req(f"https://sonarcloud.io/api/qualitygates/project_status?analysisId={analysisId}")
          qg_status = qg["projectStatus"]["status"]
          print("Quality Gate status:", qg_status)

          if qg_status != "OK":
            raise SystemExit("Quality Gate FAILED")
          PY

  build_maven:
    name: Build (Maven)
    runs-on: ubuntu-latest
    needs: [scan_gitguardian, scan_snyk, scan_sonarcloud]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Maven build
        run: mvn -B -f ${{ env.BACKEND_DIR }}/pom.xml clean verify
