name: Java CI with Codecov and MySQL

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          # Qui impostiamo la password del database nel container
          MYSQL_ROOT_PASSWORD: admin 
          MYSQL_DATABASE: second_chance
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root -padmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    # Inizializza il DB usando le tue credenziali (root/admin)
    - name: Initialize Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -padmin second_chance < db_import.sql

    - name: Build, Test and Mutation Coverage
      run: mvn clean test -P pitest

    - name: Upload coverage and test results to Codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: |
          target/site/jacoco/jacoco.xml
          target/surefire-reports/TEST-*.xml
        fail_ci_if_error: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/2chance-dependability:latest
