name: Snyk Security Scan

on: [push, pull_request]

jobs:
  scan_snyk:
    name: Scan (Snyk) - Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Snyk CLI
      - name: Setup Snyk
        uses: snyk/actions/setup@v1.0.0
        with:
          snyk-version: latest

      - name: Snyk test (fail only on High/Critical)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --severity-threshold=high